global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'k6'
    static_configs:
      - targets: ['localhost:6565']  # k6 metrics endpoint

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']  # node_exporter metrics endpoint